// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9r2JizgginJLH3T9WQG5sBst3Zd4ajTA',
    appId: '1:501853676549:web:c950b33a0a5a94150e286c',
    messagingSenderId: '501853676549',
    projectId: 'fir-flutter-codelab-d7f01',
    authDomain: 'fir-flutter-codelab-d7f01.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d7f01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgB7rOMo9L3kOTiiMV37tJkHozCsK-_is',
    appId: '1:501853676549:android:9947d63613b3a9760e286c',
    messagingSenderId: '501853676549',
    projectId: 'fir-flutter-codelab-d7f01',
    storageBucket: 'fir-flutter-codelab-d7f01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApkuotXUmJ5QcBq1O39gG0lYVlgpg-sHQ',
    appId: '1:501853676549:ios:a0381db40a431fea0e286c',
    messagingSenderId: '501853676549',
    projectId: 'fir-flutter-codelab-d7f01',
    storageBucket: 'fir-flutter-codelab-d7f01.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApkuotXUmJ5QcBq1O39gG0lYVlgpg-sHQ',
    appId: '1:501853676549:ios:a0381db40a431fea0e286c',
    messagingSenderId: '501853676549',
    projectId: 'fir-flutter-codelab-d7f01',
    storageBucket: 'fir-flutter-codelab-d7f01.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9r2JizgginJLH3T9WQG5sBst3Zd4ajTA',
    appId: '1:501853676549:web:6a15b952268f241c0e286c',
    messagingSenderId: '501853676549',
    projectId: 'fir-flutter-codelab-d7f01',
    authDomain: 'fir-flutter-codelab-d7f01.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d7f01.firebasestorage.app',
  );

}